name: MonoFaceCompute

channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8.20  
  - pytorch=2.1.0  
  - torchvision=0.16.0  
  - librosa=0.11.0  
  - loguru=0.7.3  
  - onnx=1.17.0  
  - onnx2torch=1.5.15  
  - pandas=2.0.3  
  - pip=25.0.1  
  - pyrender=0.1.45  
  - scikit-image=0.19.2 
  - scikit-learn=1.0.2  
  - scikit-video=1.1.11  
  - imgaug=0.4.0  
  - omegaconf=2.3.0  
  - hickle=5.0.3 
  - munch=4.0.0 
  - pyyaml=6.0.2 
  - tqdm=4.67.1 
  - Cython=3.0.12  
  - imageio=2.35.1  
  - pip:
    - albumentations==1.0.3  
    - compress-pickle==1.2.0  
    - chumpy==0.70  
    - face-alignment==1.3.4  
    - facenet-pytorch==2.5.2  
    - gdown==4.5.1  
    - insightface==0.6.2  
    - matplotlib==3.2.2 
    - numpy==1.23.5  
    - onnxruntime-gpu==1.19.2 
    - opencv-python-headless==4.11.0.86  
    - pytorch-lightning==2.1.3 
    - torchmetrics==1.5.2 
    - torchfile==0.1.0 
    - transformers==4.22.2  
    - trimesh==4.6.8  
    - wandb==0.19.10  
    - face-detection-tflite==0.6.0 
    - timm==1.0.15 